### ISSUE TITLE
Updated to newest instawow, stacktrace

### ISSUE THREAD

**Issue by nayab9** [layday/instawow#105]
Just updated instawow via:

`pip install --upgrade instawow
`

Looked like the upgrade worked from the output:

```
  Attempting uninstall: instawow
    Found existing installation: instawow 1.38.1
    Uninstalling instawow-1.38.1:
      Successfully uninstalled instawow-1.38.1
Successfully installed attrs-21.4.0 cattrs-22.1.0 exceptiongroup-1.0.0rc5 instawow-1.39.2 iso8601-1.0.2 prompt-toolkit-3.0.29 typing-extensions-4.2.0
```

Then i ran:

`instawow update`

and I see this:

```
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\alembic\operations\batch.py", line 643, in drop_constraint
    const = self.named_constraints.pop(cast(str, const.name))
KeyError: 'fk_pkg_dep_pkg_source_and_id'
```

Seems to also have 'encountered another stacktrace' printed after the above issue:

 ```
 File "C:\Users\xxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\instawow\migrations\versions\e13430219249_add_cascade.py", line 29, in upgrade
    batch_op.create_foreign_key(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 120, in __exit__
    next(self.gen)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\alembic\operations\base.py", line 374, in batch_alter_table
    impl.flush()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\alembic\operations\batch.py", line 138, in flush
    fn(*arg, **kw)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\alembic\operations\batch.py", line 651, in drop_constraint
    raise ValueError("No such constraint: '%s'" % const.name)
ValueError: No such constraint: 'fk_pkg_dep_pkg_source_and_id'
```

**Comment by layday** [comment]
Hi @nayab9, thanks for the report. Would you be able to install instawow from source to verify that the issue is resolved?

If you are using pip, you'd have to run it with `install -U https://github.com/layday/instawow`.

**Comment by nayab9** [comment]
> Hi @nayab9, thanks for the report. Would you be able to install instawow from source to verify that the issue is resolved?
> 
> If you are using pip, you'd have to run it with `install -U git+https://github.com/layday/instawow`.

installed from source as suggested and now seems to be working!
Thank you!!

**Comment by layday** [comment]
Great, thanks :)
