### ISSUE TITLE
PIP3 update/install of ver 1.2 ERRORS

### ISSUE THREAD

**Issue by painintheass** [layday/instawow#11]
After upgrading to version 1.2 with pip3, these errors arise:

Traceback (most recent call last):
  File "/usr/local/bin/instawow", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/instawow/cli.py", line 195, in main
    ctx.obj = manager = CliManager(config)
  File "/usr/local/lib/python3.7/site-packages/instawow/manager.py", line 327, in __init__
    if show_progress else None))
  File "/usr/local/lib/python3.7/site-packages/instawow/manager.py", line 155, in __init__
    Session = prepare_db_session(config=self.config)
  File "/usr/local/lib/python3.7/site-packages/instawow/manager.py", line 111, in prepare_db_session
    from .migrations import make_config, stamp, upgrade
ModuleNotFoundError: No module named 'instawow.migrations'

**Comment by painintheass** [comment]
As a temporary fix, I cloned THIS repo and then copied instawow/migrations folder to the "/usr/local/lib/python3.7/site-packages/instawow/" directory.

**Comment by layday** [comment]
Just more of the Python packaging clusterbungle we've all come to know and loathe.  Fixed in latest version - thanks.

**Comment by painintheass** [comment]
Understood! :-)

ver 1.2.1 fixed the issue.

Thanks for the quick response!!

**Comment by dieterdanger** [comment]
Sorry to bug you once again, but with version 1.2.1 I receive

encountered PermissionError

when I try to install or update addons.
