### ISSUE TITLE
Crash on 1.46.0

### ISSUE THREAD

**Issue by xIGBClutchIx** [layday/instawow#119]
Updated now look to be instantly crashing on startup.

```
Traceback (most recent call last):
  File "app\instawow_gui_wrapper\__main__.py", line 32, in <module>
  File "app\instawow_gui_wrapper\__main__.py", line 28, in main
  File "app_packages\loguru\_logger.py", line 1226, in catch_wrapper
  File "app_packages\click\core.py", line 1130, in __call__
  File "app_packages\click\core.py", line 1055, in main
  File "app_packages\click\core.py", line 1657, in invoke
  File "app_packages\click\core.py", line 1404, in invoke
  File "app_packages\click\core.py", line 760, in invoke
  File "app_packages\click\decorators.py", line 26, in new_func
  File "app_packages\instawow\cli.py", line 1141, in gui
  File "app_packages\instawow_gui\app.py", line 18, in __init__
  File "app_packages\toga\app.py", line 278, in __init__
  File "app_packages\toga\platform.py", line 53, in get_platform_factory
  File "app_packages\toga_winforms\factory.py", line 1, in <module>
  File "app_packages\toga_winforms\app.py", line 7, in <module>
  File "app_packages\toga_winforms\keys.py", line 6, in <module>
  File "app_packages\toga_winforms\libs\__init__.py", line 1, in <module>
  File "app_packages\toga_winforms\libs\fonts.py", line 13, in <module>
  File "app_packages\toga_winforms\libs\winforms.py", line 3, in <module>
  File "app_packages\clr.py", line 5, in <module>
  File "app_packages\pythonnet\__init__.py", line 9, in <module>
AttributeError: module 'clr_loader' has no attribute 'wrappers'
```

**Comment by layday** [comment]
Thanks for the report. This should be fixed in https://github.com/layday/instawow/releases/tag/v1.46.0.post1.

**Comment by xIGBClutchIx** [comment]
Perfect, thank you very much!
