### ISSUE TITLE
CLI 2.1.0 Windows binary fails to start

### ISSUE THREAD

**Issue by protocolist** [layday/instawow#127]
After extracting the archive from the releases page and running instawow-standalone.exe the console reports:

```
Traceback (most recent call last):
  File "Lib\site-packages\instawow\__main__.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "instawow\cli.py", line 18, in <module>
    from . import __version__, _deferred_types, db, models
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "instawow\models.py", line 16, in <module>
    from .resolvers import Defn
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "instawow\resolvers.py", line 15, in <module>
    from . import _deferred_types, manager, models
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "instawow\manager.py", line 25, in <module>
    from ._sources.cfcore import CfCoreResolver
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "instawow\_sources\cfcore.py", line 23, in <module>
    from ..resolvers import BaseResolver, Defn, HeadersIntent
ImportError: cannot import name 'BaseResolver' from partially initialized module 'instawow.resolvers' (most likely due to a circular import) (C:\Users\u\Downloads\instawow-cli-2.1.0-windows-latest\instawow\resolvers.pyc)
[23540] Failed to execute script '__main__' due to unhandled exception!
```

I was able to reproduce the behavior on the following Windows client OS:

- Windows 11 Enterprise 22H2 22621.819
- Windows 10 LTSC 2021 (21H2) 19044.2364

Previous version of Instawow continues to work on both.

Screenshot of console output:
![instawow](https://user-images.githubusercontent.com/60244403/207743398-6b96cdae-2db9-4489-83ab-16fccbbe96d6.png)

**Comment by layday** [comment]
Thanks for the report. This should be fixed in https://github.com/layday/instawow/releases/tag/v2.1.1.
