### ISSUE TITLE
Windows 2.2.0 install fails (Windows 10 Pro)

### ISSUE THREAD

**Issue by j-hickman** [layday/instawow#130]
After a direct upgrade (msi) from 2.1.1 to 2.2.0, this error pops up:

```
Traceback (most recent call last):
  File "app\instawow_gui_wrapper\__main__.py", line 32, in <module>
  File "app\instawow_gui_wrapper\__main__.py", line 28, in main
  File "app_packages\loguru\_logger.py", line 1251, in catch_wrapper
  File "app_packages\click\core.py", line 1130, in __call__
  File "app_packages\click\core.py", line 1055, in main
  File "app_packages\click\core.py", line 1657, in invoke
  File "app_packages\click\core.py", line 1404, in invoke
  File "app_packages\click\core.py", line 760, in invoke
  File "app_packages\click\decorators.py", line 26, in new_func
  File "app_packages\instawow\cli.py", line 1209, in gui
  File "app_packages\instawow_gui\app.py", line 23, in __init__
  File "app_packages\toga\app.py", line 323, in __init__
  File "app_packages\toga\platform.py", line 73, in get_platform_factory
RuntimeError: No Toga backend could be loaded.
```

I suspect there's a missing dependency not in the msi package for 2.2.0

**Comment by layday** [comment]
I can't repro this. Could you try uninstalling and reinstalling? The dependencies are all there.

**Comment by j-hickman** [comment]
Yes, I tried a full uninstall and reinstall using the 2.2.0 msi.  I reinstalled 2.1.1 and it works fine.

**Comment by j-hickman** [comment]
I also tried 2.3.0 (latest release) and it has identical errors to this issue.

`Traceback (most recent call last):
  File "app\instawow_gui_wrapper\__main__.py", line 32, in <module>
  File "app\instawow_gui_wrapper\__main__.py", line 28, in main
  File "app_packages\loguru\_logger.py", line 1251, in catch_wrapper
  File "app_packages\click\core.py", line 1130, in __call__
  File "app_packages\click\core.py", line 1055, in main
  File "app_packages\click\core.py", line 1657, in invoke
  File "app_packages\click\core.py", line 1404, in invoke
  File "app_packages\click\core.py", line 760, in invoke
  File "app_packages\click\decorators.py", line 26, in new_func
  File "app_packages\instawow\cli.py", line 1212, in gui
  File "app_packages\instawow_gui\app.py", line 23, in __init__
  File "app_packages\toga\app.py", line 323, in __init__
  File "app_packages\toga\platform.py", line 73, in get_platform_factory
RuntimeError: No Toga backend could be loaded.
`

**Comment by layday** [comment]
Could you please check if there is a `toga_winforms-0.3.1.dist-info` folder in `app_packages`? It should have an `entry_points.txt` inside.

**Comment by j-hickman** [comment]
![image](https://user-images.githubusercontent.com/97261625/235219814-e37e5892-217e-4491-94fd-0dfd4684829b.png)

The directory appears to be there, but entry_points.txt is not.

**Comment by layday** [comment]
That's "toga-0.3.1.dist-info"; we are looking for "toga_winforms-0.3.1.dist-info" :)

**Comment by j-hickman** [comment]
Yes, contents are:

> [toga.backends]
> windows = toga_winforms

**Comment by layday** [comment]
Just to understand this is a little better, you launch `instawow-gui.exe` and then that error pops up on the screen - where? In an alert?

**Comment by j-hickman** [comment]
Starting the app (yes, instawow-gui.exe) the error pops up in an application dialog box: 

![image](https://user-images.githubusercontent.com/97261625/235228217-b7726403-e7ff-4c8d-a134-c45c37029dbc.png)

Then closes, it never properly starts.

**Comment by j-hickman** [comment]
Of note, in case this comes up, I also tried right clicking on the MSI and doing a repair. It didn't resolve the issue (for 2.2.0 or 2.3.0).

**Comment by layday** [comment]
Could you give the version from https://github.com/layday/instawow/actions/runs/4833972401 a shot?

**Comment by j-hickman** [comment]
Sure, tried it.  No change, same error.  If there's a way to turn on debugging for you and provide you the result, I can do that as well.

**Comment by layday** [comment]
You might be able to find a more complete stack trace in `%APPDATA%/Roaming/instawow/profiles/__jsonrpc__/error.log`.

**Comment by layday** [comment]
Could you try the version from https://github.com/layday/instawow/actions/runs/4838097274? It'll log a few more things in your `error.log` that should hopefully help with debugging the issue.

**Comment by layday** [comment]
What I assume happened is that an old upgrade failed, and since that particular folder wasn't in any of the newer installers' manifests, it just stayed there until it tripped up the new backend finder in the latest version of `toga`, which depends on the presence of `entry_points.txt`.  I (briefly) discussed this with the developers of the upstream library and we can't definitvely say why `dist-info` was cleared out but the uninstaller failed to delete the folder.  Perhaps instawow was running at the time and had a handle on the folder?  Maybe the uninstaller was interrupted? Not sure.  I suppose it'd be better if the uninstaller were simply to delete everything under "layday/instawow", but I'd have to look into how to configure it to do that.

**Comment by layday** [comment]
Also opened https://github.com/python/importlib_metadata/issues/457 to avoid silent failures like we've seen here.
