### ISSUE TITLE
Apparently Curse moved addons to a different domain name

### ISSUE THREAD

**Issue by Zireael-N** [layday/instawow#2]
For example, if you visit https://mods.curse.com/addons/wow/big-wigs, it redirects you to https://www.curseforge.com/wow/addons/big-wigs. That domain was up before, but URIs were a bit different, so `instawow` currently fails:

```
$ instawow install https://www.curseforge.com/wow/addons/big-wigs
Resolving add-ons
Installing
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\instawow\cli.py", line 149, in install
    raise result
  File "c:\program files\python36\lib\site-packages\instawow\manager.py", line 37, in _intercept_fut
    result = await fut
  File "c:\program files\python36\lib\site-packages\instawow\manager.py", line 217, in _prepare_install
    new_pkg = await self._resolve(origin, id_or_slug, strategy)
  File "c:\program files\python36\lib\site-packages\instawow\manager.py", line 205, in _resolve
    raise PkgOriginInvalid
instawow.manager.PkgOriginInvalid
```

**Comment by layday** [comment]
What is the output of `instawow --version` for you?  Though that doesn't work it also shouldn't have raised an error.

**Comment by Zireael-N** [comment]
It was related to the cross/tick issue I reported in #3. Fixing that makes this output a human-readable text rather than raise an exception.
