### ISSUE TITLE
instawow upgrade failure

### ISSUE THREAD

**Issue by nayab9** [layday/instawow#21]
instawow was out of date, so I attempted to update it, and i now see the following message:

Traceback (most recent call last):
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\instawow\cli.py", line 148, in create_config
    return Config.read().write()
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\instawow\config.py", line 62, in read
    .read_text(encoding='utf-8'))
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\pathlib.py", line 1199, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\pathlib.py", line 1186, in open
    opener=self._opener)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\pathlib.py", line 1039, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\gamer\\AppData\\Roaming\\instawow\\config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gamer\AppData\Local\Programs\Python\Python37\Scripts\instawow-script.py", line 11, in <module>
    load_entry_point('instawow==1.3.0', 'console_scripts', 'instawow')()
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\instawow\cli.py", line 188, in main
    config = create_config()
  File "c:\users\gamer\appdata\local\programs\python\python37\lib\site-packages\instawow\cli.py", line 151, in create_config
    import readline
ModuleNotFoundError: No module named 'readline'

**Comment by layday** [comment]
This should be fixed in v1.3.1.  Thanks for the report.

**Comment by nayab9** [comment]
Thank you! It seems to be fixed now, here is what the output was though, looked a little bit stranger, and I had to re-enter my addon directory - but all seems to be well at this point:

Successfully installed instawow-1.3.1

C:\Users\gamer>instawow update
[34m![0m configuration not found
  [33m>[0m add-on folder: C:\Program Files (x86)\World of Warcraft\_retail_\Interface\AddOns

**Comment by layday** [comment]
It looks like the ANSI colour codes weren't stripped from the output.  I'll fix it in a later patch.
