### ISSUE TITLE
Can't read non-utf8 .toc files that include non-ascii characters.

### ISSUE THREAD

**Issue by kurumushi** [layday/instawow#25]
The .toc for [SmartBuff Classic](https://www.curseforge.com/wow/addons/smartbuff-classic) is encoded as iso-8859-1. when instawow encounters this file during a reconcile, it gives the following error:
```Traceback (most recent call last):
  File "/home/kris/.local/instawow/.venv/bin/instawow", line 11, in <module>
    load_entry_point('instawow==1.5.1.dev4+gaf69a97', 'console_scripts', 'instawow')()
  File "/home/kris/.local/instawow/.venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kris/.local/instawow/.venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kris/.local/instawow/.venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kris/.local/instawow/.venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kris/.local/instawow/.venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kris/.local/instawow/.venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/kris/.local/instawow/.venv/lib/python3.7/site-packages/instawow-1.5.1.dev4+gaf69a97-py3.7.egg/instawow/cli.py", line 343, in reconcile
    for selections in match_all():
  File "/home/kris/.local/instawow/.venv/lib/python3.7/site-packages/instawow-1.5.1.dev4+gaf69a97-py3.7.egg/instawow/cli.py", line 323, in match_all
    groups = fn(get_leftovers())
  File "/home/kris/.local/instawow/.venv/lib/python3.7/site-packages/instawow-1.5.1.dev4+gaf69a97-py3.7.egg/instawow/cli.py", line 270, in match_toc_ids_from_sources
    [])
  File "/home/kris/.local/instawow/.venv/lib/python3.7/site-packages/instawow-1.5.1.dev4+gaf69a97-py3.7.egg/instawow/cli.py", line 268, in <genexpr>
    (([t], {Defn(ids_to_sources[v.key], v.value) for v in i if v})
  File "/home/kris/.local/instawow/.venv/lib/python3.7/site-packages/instawow-1.5.1.dev4+gaf69a97-py3.7.egg/instawow/cli.py", line 266, in <genexpr>
    maybe_ids = (((n, r), (r[i] for i in ids_to_sources)) for n, r in dir_tocs)
  File "/home/kris/.local/instawow/.venv/lib/python3.7/site-packages/instawow-1.5.1.dev4+gaf69a97-py3.7.egg/instawow/cli.py", line 265, in <genexpr>
    dir_tocs = ((n, TocReader_(n)) for n in sorted(leftovers))
  File "/home/kris/.local/instawow/.venv/lib/python3.7/site-packages/instawow-1.5.1.dev4+gaf69a97-py3.7.egg/instawow/cli.py", line 224, in <lambda>
    TocReader_ = lambda n: TocReader.from_path_name(manager.config.addon_dir / n)
  File "/home/kris/.local/instawow/.venv/lib/python3.7/site-packages/instawow-1.5.1.dev4+gaf69a97-py3.7.egg/instawow/utils.py", line 65, in from_path_name
    return cls.from_path(path / f'{path.name}.toc', *args, **kwargs)
  File "/home/kris/.local/instawow/.venv/lib/python3.7/site-packages/instawow-1.5.1.dev4+gaf69a97-py3.7.egg/instawow/utils.py", line 61, in from_path
    return cls(path.read_text(encoding='utf-8-sig'), *args, **kwargs)
  File "/usr/lib/python3.7/pathlib.py", line 1207, in read_text
    return f.read()
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
  File "/usr/lib/python3.7/encodings/utf_8_sig.py", line 69, in _buffer_decode
    return codecs.utf_8_decode(input, errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 359: invalid start byte
```

If I convert the .toc file to UTF-8, the file is read with no problems.

**Comment by layday** [comment]
I've given this the bare minimum of, um, thought and I feel like pulling in something like libmagic for charset detection would be overkill.  It's easier to assume whatever encoding's used is extended from ASCII, which also happens to be the case with ISO 8859-1.  It looks this is what WoW itself is doing - note the mojibake:

<img width="799" alt="Screenshot 2019-10-06 at 16 16 54" src="https://user-images.githubusercontent.com/31134424/66269733-efd32580-e854-11e9-94f7-c594e868758f.png">

It would make sense for *instawow* to take the same approach.

**Comment by layday** [comment]
Thanks for the report!
