### ISSUE TITLE
ubuntu release, 1.8.1, config not found

### ISSUE THREAD

**Issue by torkus** [layday/instawow#32]
hey @layday , I just downloaded [this release](https://github.com/layday/instawow/releases/download/v1.8.1/instawow-ubuntu-latest.zip), unzipped it in my `/tmp` dir, did a `chmod` and then `./instawow` - was very impressed with the speed and autocompletion and prompts, but then it died:

```
0 ✓ (9.788s) 00:35:07 tmp $ unzip instawow-ubuntu-latest.zip 
Archive:  instawow-ubuntu-latest.zip
  inflating: instawow                
0 ✓ (821ms) 00:35:11 tmp $ chmod +x instawow
0 ✓ (8.4ms) 00:35:16 tmp $ ./instawow 
Usage: instawow [OPTIONS] COMMAND [ARGS]...

  Add-on manager for World of Warcraft.

Options:
  --version   Show the version and exit.
  --debug     Log more things.
  -h, --help  Show this message and exit.

Commands:
  configure            Configure instawow.
  install              Install add-ons.
  list                 List installed add-ons.
  list-folders         List add-on folders.
  reconcile            Reconcile pre-installed add-ons.
  remove               Remove add-ons.
  reveal               Open an add-on folder in your file manager.
  search               Search for add-ons to install.
  update               Update installed add-ons.
  visit                Open an add-on's homepage in your browser.
  weakauras-companion  Manage your WeakAuras.
0 ✓ (109ms) 00:35:18 tmp $ ./instawow  list
Add-on directory: /home/torkus/foo/                                                                                                                                            
Game flavour: retail                                                                                                                                                           
Traceback (most recent call last):
  File "instawow.cli", line 83, in m
  File "instawow.config", line 52, in read
  File "pathlib", line 1216, in read_text
  File "pathlib", line 1203, in open
  File "pathlib", line 1058, in _opener
FileNotFoundError: [Errno 2] No such file or directory: '/home/torkus/.config/instawow/config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "instawow.__main__", line 4, in <module>
  File "click.core", line 829, in __call__
  File "click.core", line 782, in main
  File "click.core", line 1257, in invoke
  File "click.core", line 700, in make_context
  File "click.core", line 1048, in parse_args
  File "click.core", line 1630, in handle_parse_result
  File "click.core", line 123, in invoke_param_callback
  File "instawow.cli", line 150, in <lambda>
  File "instawow.utils", line 83, in __get__
  File "instawow.cli", line 86, in m
  File "click.core", line 610, in invoke
  File "click.decorators", line 33, in new_func
  File "instawow.cli", line 487, in configure
  File "instawow.config", line 64, in write
  File "instawow.config", line 57, in ensure_dirs
  File "pathlib", line 1268, in mkdir
FileExistsError: [Errno 17] File exists: '/tmp/instawow'
SystemError
```

**Comment by layday** [comment]
Hi @torkus, thanks for the report (and praise). Did you try this on Ubuntu or another Linux OS? It looks like `mkdir` might ignore the `exist_ok` parameter but I cannot reproduce it under Ubuntu. Is your `/tmp/instawow` a directory?

**Comment by torkus** [comment]
I'm running Arch Linux, `/tmp/instawow` is the binary I unzipped

**Comment by layday** [comment]
Well, that explains it. instawow attempts to create `/tmp/instawow` as a temporary directory to use but since it already exists and it is not a directory, it crashes.  I did not consider the possibility that somebody would unzip the instawow binary at `/tmp/instawow`.

**Comment by torkus** [comment]
perhaps [here](https://github.com/layday/instawow/blob/5d4601b689294b20d377825e899d907e283ce6dc/instawow/config.py#L27) you might use [one of these](https://docs.python.org/3.8/library/tempfile.html#tempfile.mkdtemp)

**Comment by torkus** [comment]
beat me to it ;)

**Comment by torkus** [comment]
yes, this is much better:

```
1 ✗ (1.120s) 01:13:41 tmp $ mv instawow foobar
0 ✓ (5.2ms) 01:19:12 tmp $ ./foobar 
Usage: foobar [OPTIONS] COMMAND [ARGS]...

  Add-on manager for World of Warcraft.

Options:
  --version   Show the version and exit.
  --debug     Log more things.
  -h, --help  Show this message and exit.

Commands:
  configure            Configure instawow.
  install              Install add-ons.
  list                 List installed add-ons.
  list-folders         List add-on folders.
  reconcile            Reconcile pre-installed add-ons.
  remove               Remove add-ons.
  reveal               Open an add-on folder in your file manager.
  search               Search for add-ons to install.
  update               Update installed add-ons.
  visit                Open an add-on's homepage in your browser.
  weakauras-companion  Manage your WeakAuras.
0 ✓ (109ms) 01:19:14 tmp $ ./foobar list
Add-on directory: /home/torkus/foo                                                                                                                                             
Game flavour: retail                                                                                                                                                           
Configuration written to: /home/torkus/.config/instawow/config.json
curse:adibags
```

although ... 

```
$ ll ~/foo
total 80M
drwxr-xr-x 1 torkus torkus 7.0K Mar 16 23:42  .
drwx------ 1 torkus torkus 1.5K Apr 26 13:40  ..
drwxr-xr-x 1 torkus torkus  396 Oct 19  2019  AtlasLoot
drwxr-xr-x 1 torkus torkus  100 Oct 19  2019  AtlasLoot_BattleforAzeroth
drwxr-xr-x 1 torkus torkus  116 Oct 19  2019  AtlasLoot_BurningCrusade
drwxr-xr-x 1 torkus torkus   86 Oct 19  2019  AtlasLoot_Cataclysm
drwxr-xr-x 1 torkus torkus   82 Oct 19  2019  AtlasLoot_Classic
drwxr-xr-x 1 torkus torkus  106 Oct 19  2019  AtlasLoot_Collections
drwxr-xr-x 1 torkus torkus   84 Oct 19  2019  AtlasLoot_Crafting
drwxr-xr-x 1 torkus torkus   84 Oct 19  2019  AtlasLoot_Factions
drwxr-xr-x 1 torkus torkus   80 Oct 19  2019  AtlasLoot_Legion
drwxr-xr-x 1 torkus torkus  118 Oct 19  2019  AtlasLoot_MistsofPandaria
drwxr-xr-x 1 torkus torkus  114 Oct 19  2019  AtlasLoot_Options
drwxr-xr-x 1 torkus torkus   74 Oct 19  2019  AtlasLoot_PvP
drwxr-xr-x 1 torkus torkus  102 Oct 19  2019  AtlasLoot_WarlordsofDraenor
drwxr-xr-x 1 torkus torkus   90 Oct 19  2019  AtlasLoot_WorldEvents
drwxr-xr-x 1 torkus torkus  104 Oct 19  2019  AtlasLoot_WrathoftheLichKing
drwxr-xr-x 1 torkus torkus  586 Oct 19  2019  Auc-Advanced
drwxr-xr-x 1 torkus torkus  124 Mar 16 23:41  Auc-Filter-Basic
drwxr-xr-x 1 torkus torkus  108 Mar 16 23:41  Auc-ScanData
drwxr-xr-x 1 torkus torkus  102 Mar 16 23:41  Auc-Stat-Histogram
drwxr-xr-x 1 torkus torkus   82 Mar 16 23:41  Auc-Stat-iLevel
drwxr-xr-x 1 torkus torkus  102 Mar 16 23:41  Auc-Stat-Purchased
drwxr-xr-x 1 torkus torkus   90 Mar 16 23:41  Auc-Stat-Simple
drwxr-xr-x 1 torkus torkus   90 Mar 16 23:41  Auc-Stat-StdDev
drwxr-xr-x 1 torkus torkus  110 Mar 16 23:41  Auc-Util-FixAH
drwxr-xr-x 1 torkus torkus   88 Oct 19  2019  AutoLootPlus
drwxr-xr-x 1 torkus torkus  212 Oct 19  2019  AutomaticGoblinTherapist
drwxr-xr-x 1 torkus torkus  258 Dec 31 17:39  AzeritePowerWeights
drwxr-xr-x 1 torkus torkus  156 Oct 19  2019  BagBrother
drwxr-xr-x 1 torkus torkus  158 Feb 23 12:46  Bagnon
drwxr-xr-x 1 torkus torkus   86 Oct 19  2019  Bagnon_Config
drwxr-xr-x 1 torkus torkus  100 Oct 19  2019  Bagnon_GuildBank
drwxr-xr-x 1 torkus torkus  128 Oct 19  2019  Bagnon_VoidStorage
drwxr-xr-x 1 torkus torkus  624 Oct 19  2019  Bartender4
drwxr-xr-x 1 torkus torkus  662 Mar 16 23:41  BeanCounter
drwxr-xr-x 1 torkus torkus  200 Oct 19  2019  BigWigs
drwxr-xr-x 1 torkus torkus  296 Oct 19  2019  BigWigs_Azeroth
drwxr-xr-x 1 torkus torkus  506 Oct 19  2019  BigWigs_BattleOfDazaralor
drwxr-xr-x 1 torkus torkus  230 Oct 19  2019  BigWigs_Core
drwxr-xr-x 1 torkus torkus  166 Oct 19  2019  BigWigs_CrucibleOfStorms
drwxr-xr-x 1 torkus torkus  418 Oct 19  2019  BigWigs_EternalPalace
drwxr-xr-x 1 torkus torkus  388 Feb 23 12:46  BigWigs_Nyalotha
drwxr-xr-x 1 torkus torkus  130 Oct 19  2019  BigWigs_Options
drwxr-xr-x 1 torkus torkus  474 Oct 19  2019  BigWigs_Plugins
drwxr-xr-x 1 torkus torkus  282 Oct 19  2019  BigWigs_Uldir
drwxr-xr-x 1 torkus torkus  414 Oct 19  2019  Carbonite
drwxr-xr-x 1 torkus torkus  438 Oct 19  2019  DBM-AQ20
drwxr-xr-x 1 torkus torkus  510 Oct 19  2019  DBM-AQ40
drwxr-xr-x 1 torkus torkus  348 Oct 19  2019  DBM-Azeroth
drwxr-xr-x 1 torkus torkus  628 Feb 23 12:46  DBM-Azeroth-BfA
drwxr-xr-x 1 torkus torkus  588 Oct 19  2019  DBM-BlackTemple
drwxr-xr-x 1 torkus torkus  684 Oct 19  2019  DBM-Brawlers
drwxr-xr-x 1 torkus torkus  514 Oct 19  2019  DBM-BWL
drwxr-xr-x 1 torkus torkus 1.1K Oct 19  2019  DBM-Core
drwxr-xr-x 1 torkus torkus  462 Oct 19  2019  DBM-CrucibleofStorms
drwxr-xr-x 1 torkus torkus  120 Oct 19  2019  DBM-DefaultSkin
drwxr-xr-x 1 torkus torkus  560 Oct 19  2019  DBM-DMF
drwxr-xr-x 1 torkus torkus  818 Feb 23 12:46  DBM-EternalPalace
drwxr-xr-x 1 torkus torkus  660 Oct 19  2019  DBM-GUI
drwxr-xr-x 1 torkus torkus  482 Oct 19  2019  DBM-Hyjal
drwxr-xr-x 1 torkus torkus  772 Oct 19  2019  DBM-Karazhan
drwxr-xr-x 1 torkus torkus  540 Oct 19  2019  DBM-MC
drwxr-xr-x 1 torkus torkus  714 Feb 23 12:46  DBM-Nyalotha
drwxr-xr-x 1 torkus torkus  504 Oct 19  2019  DBM-Outlands
drwxr-xr-x 1 torkus torkus  600 Oct 19  2019  DBM-Party-BfA
drwxr-xr-x 1 torkus torkus  490 Oct 19  2019  DBM-Serpentshrine
drwxr-xr-x 1 torkus torkus  116 Oct 19  2019  DBM-StatusBarTimers
drwxr-xr-x 1 torkus torkus  536 Oct 19  2019  DBM-Sunwell
drwxr-xr-x 1 torkus torkus  410 Oct 19  2019  DBM-TheEye
drwxr-xr-x 1 torkus torkus  574 Oct 19  2019  DBM-Uldir
drwxr-xr-x 1 torkus torkus  502 Feb 23 12:46  DBM-WorldEvents
drwxr-xr-x 1 torkus torkus  674 Oct 19  2019  DBM-ZuldazarRaid
drwxr-xr-x 1 torkus torkus  666 Mar 16 23:41  Enchantrix
drwxr-xr-x 1 torkus torkus  370 Mar 16 23:41  Enchantrix-Barker
drwxr-xr-x 1 torkus torkus  336 Oct 19  2019  GatherMate2
drwxr-xr-x 1 torkus torkus  304 Oct 19  2019  Grid
drwxr-xr-x 1 torkus torkus 1.6K Oct 19  2019  GTFO
drwxr-xr-x 1 torkus torkus  810 Feb 23 12:46  HealBot
drwxr-xr-x 1 torkus torkus  128 Oct 19  2019  HealBot_br
drwxr-xr-x 1 torkus torkus  128 Oct 19  2019  HealBot_cn
drwxr-xr-x 1 torkus torkus   88 Feb 23 12:46  HealBot_Data
drwxr-xr-x 1 torkus torkus  128 Oct 19  2019  HealBot_de
drwxr-xr-x 1 torkus torkus  220 Feb 23 12:46  HealBot_en
drwxr-xr-x 1 torkus torkus  128 Oct 19  2019  HealBot_es
drwxr-xr-x 1 torkus torkus  128 Oct 19  2019  HealBot_fr
drwxr-xr-x 1 torkus torkus  128 Oct 19  2019  HealBot_gr
drwxr-xr-x 1 torkus torkus  128 Oct 19  2019  HealBot_hu
drwxr-xr-x 1 torkus torkus  128 Oct 19  2019  HealBot_it
drwxr-xr-x 1 torkus torkus  128 Oct 19  2019  HealBot_kr
drwxr-xr-x 1 torkus torkus  172 Feb 23 12:46  HealBot_Options
drwxr-xr-x 1 torkus torkus  128 Oct 19  2019  HealBot_ru
drwxr-xr-x 1 torkus torkus  128 Feb 23 12:46  HealBot_Tips
drwxr-xr-x 1 torkus torkus  128 Oct 19  2019  HealBot_tw
drwxr-xr-x 1 torkus torkus  148 Oct 19  2019  ImprovedLootFrame
drwxr-xr-x 1 torkus torkus  360 Mar 16 23:41  Informant
drwxr-xr-x 1 torkus torkus  442 Oct 19  2019  MasterPlan
drwxr-xr-x 1 torkus torkus   54 Oct 19  2019  MasterPlanA
drwxr-xr-x 1 torkus torkus  540 Oct 19  2019  MuffinFactionizer
drwxr-xr-x 1 torkus torkus  332 Oct 19  2019  NPCScan
drwxr-xr-x 1 torkus torkus  200 Mar 16 23:41  OmniCC
drwxr-xr-x 1 torkus torkus  156 Mar 16 23:41  OmniCC_Config
drwxr-xr-x 1 torkus torkus  200 Oct 19  2019  OPie
drwxr-xr-x 1 torkus torkus  710 Oct 19  2019  Recount
drwxr-xr-x 1 torkus torkus  188 Oct 19  2019  SaySapped
drwxr-xr-x 1 torkus torkus  348 Oct 19  2019  Skada
drwxr-xr-x 1 torkus torkus  144 Mar 16 23:41  SlideBar
drwxr-xr-x 1 torkus torkus  136 Mar 16 23:41  Stubby
drwxr-xr-x 1 torkus torkus  116 Mar 16 23:41 '!Swatter'
drwxr-xr-x 1 torkus torkus  508 Oct 19  2019  TidyPlates
drwxr-xr-x 1 torkus torkus  358 Oct 19  2019  TidyPlates_Graphite
drwxr-xr-x 1 torkus torkus  324 Oct 19  2019  TidyPlates_Grey
drwxr-xr-x 1 torkus torkus  192 Oct 19  2019  TidyPlatesHub
drwxr-xr-x 1 torkus torkus  624 Oct 19  2019  TidyPlates_Neon
drwxr-xr-x 1 torkus torkus  568 Oct 19  2019  TidyPlates_Quatre
drwxr-xr-x 1 torkus torkus  526 Oct 19  2019  TidyPlatesWidgets
drwxr-xr-x 1 torkus torkus  674 Oct 19  2019  Titan
drwxr-xr-x 1 torkus torkus  120 Oct 19  2019  TitanBag
drwxr-xr-x 1 torkus torkus  108 Oct 19  2019  TitanClock
drwxr-xr-x 1 torkus torkus  116 Oct 19  2019  TitanGold
drwxr-xr-x 1 torkus torkus  160 Oct 19  2019  TitanLocation
drwxr-xr-x 1 torkus torkus  160 Oct 19  2019  TitanLootType
drwxr-xr-x 1 torkus torkus  184 Oct 19  2019  TitanPerformance
drwxr-xr-x 1 torkus torkus  144 Oct 19  2019  TitanRepair
drwxr-xr-x 1 torkus torkus  128 Oct 19  2019  TitanVolume
drwxr-xr-x 1 torkus torkus   90 Oct 19  2019  TitanXP
drwxrwxrwx 1 torkus torkus  214 Feb 23 12:46  TradeSkillMaster
drwxr-xr-x 1 torkus torkus  138 Dec 31 17:40  Tukui
drwxr-xr-x 1 torkus torkus  102 Dec 31 17:40  Tukui_Config
drwxr-xr-x 1 torkus torkus  116 Dec 31 17:40  Tukui_RoleIcons
drwxr-xr-x 1 torkus torkus  630 Feb 23 12:46  WeakAuras
drwxr-xr-x 1 torkus torkus  104 Feb 23 12:46  WeakAurasArchive
drwxr-xr-x 1 torkus torkus   98 Oct 19  2019  WeakAurasModelPaths
drwxr-xr-x 1 torkus torkus  608 Oct 19  2019  WeakAurasOptions
drwxr-xr-x 1 torkus torkus  220 Oct 19  2019  WeakAurasTemplates
```

it's only picking up adibags :(

**Comment by layday** [comment]
As a stopgap you can move the binary or override the temporary directory value using `instawow_temp_dir=/tmp/instawow-tmp ./instawow`.

**Comment by layday** [comment]
Reconciliation is not automatic in instawow, you're gonna have to run `instawow reconcile`. `list` only lists the add-ons you've installed using instawow.

**Comment by torkus** [comment]
Fair enough. I like how I get to pick the source during reconciliation.

**Comment by layday** [comment]
There's also a promptless option (`instawow reconcile -a`) though it's not advertised.  I'm making a mental note to mention that in the reconciliation 'preamble' :)

**Comment by layday** [comment]
Thanks for taking the time to try out instawow and opening a report.

**Comment by torkus** [comment]
I seemed to have played with instawow before which is why it was picking up adibags even though that directory wasn't in `~/foo`.

> Thanks for taking the time to try out instawow and opening a report

No worries. I personally would just have a temporary directory prefixed with 'instawow' rather than a hardcoded `$tempdir/instawow/` but I'll leave that up to you. Feel free to close the ticket if you like.

**Comment by layday** [comment]
The problem with that is the temporary directory is (also) used as a semi-persistent cache so I'd like to be able to refer to it.  Letting the OS clear out add-on zip files and old catalogues for me is convenient.  When they're there they might save the user a round trip - and if they don't exist, well, it's no biggie.

**Comment by layday** [comment]
I think I'll put this one on the backburner. The whole caching mechanism does probably require rethinking but I think it fairly unlikely that a user would stumble on this issue.  Thanks for taking the time to open a bug report - I appreciate it.
