### ISSUE TITLE
Error on instawow update

### ISSUE THREAD

**Issue by toastmonger** [layday/instawow#4]
In the last couple of days been getting the following error (fingers crossed you're still updating this, thanks in advance!).  I use both wow interface and curse.

```
Traceback (most recent call last):
  File "/usr/local/bin/instawow", line 11, in <module>
    load_entry_point('instawow==0.4', 'console_scripts', 'instawow')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/instawow/cli.py", line 131, in update
    raise result
  File "/usr/local/lib/python3.6/site-packages/instawow/manager.py", line 158, in update
    new_pkg = await self.resolve(origin, id_or_slug, old_pkg.options.strategy)
  File "/usr/local/lib/python3.6/site-packages/instawow/manager.py", line 119, in resolve
    .resolve(id_or_slug, strategy=strategy)
  File "/usr/local/lib/python3.6/site-packages/instawow/resolvers.py", line 96, in resolve
    p_id = int(parse_html(text).xpath('string(//div[text() = "Project ID "]'
ValueError: invalid literal for int() with base 10: ''
```

**Comment by layday** [comment]
You seem to have an older version of instawow that relied on scraping bits and bobs from CurseForge project pages.  Run `pip3 install -U instawow` to upgrade.

**Comment by toastmonger** [comment]
Yes, that was it, thanks for sorting out my mistake!
