### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'MainThread'. during reconcile

### ISSUE THREAD

**Issue by ciphersimian** [layday/instawow#43]
Ran it again with --debug after and it finished the job without further incident.

```
$ ./instawow -p wow1 reconcile --auto
✓ curse:acp
  installed 3.5.7
✓ curse:advancedinterfaceoptions
  installed 1.3.4
✓ curse:ark-inventory
  installed 3.09.35
✓ curse:bad-boy
  installed v8.2.5
✓ curse:bank-stack
  installed v80200.0
✓ curse:bartender4
  installed 4.9.0
✓ curse:betterbattlepettooltip
  installed 8.0.0.0
✓ curse:candy-buckets
  installed v8.3.0.200703
✓ wowi:12326-chocolatebar-broker-display
  installed v3.3.5
✓ curse:copypasta
  installed 1.1.2
✓ curse:deadly-boss-mods
  installed 8.3.33
✓ curse:dejacharacterstats
  installed 830r306
✓ curse:fishingbuddy
  installed 1.10.10
✓ curse:gladiatorlossa
  installed 2.3.6
✓ curse:grid2
  installed r955
✓ curse:handynotes
  installed v1.5.10
✓ curse:instance-achievement-tracker
  installed V2.80.0-Release
✓ curse:masque
  installed 8.2.8
✓ curse:masque-caith
  installed 8.2.6
✓ curse:prat-3-0
  installed 3.8.26
✓ curse:quartz
  installed 3.5.2
✓ curse:rsa
  installed r532-release
✓ curse:raid_checklist
  installed 6.1.2.0
✓ curse:sexymap
  installed v8.3.0
✓ curse:shadowed-unit-frames
  installed v4.2.9
✓ curse:tellmewhen
  installed 8.7.5
✓ curse:weakauras-2
  installed 2.18.2
✓ curse:ora3
  installed v8.3.2
✓ curse:libpetjournal-2-0
  installed 2.0.33
Traceback (most recent call last):
  File "instawow.__main__", line 4, in <module>
  File "click.core", line 829, in __call__
  File "click.core", line 782, in main
  File "click.core", line 1259, in invoke
  File "click.core", line 1066, in invoke
  File "click.core", line 610, in invoke
  File "click.decorators", line 21, in new_func
  File "instawow.cli", line 475, in reconcile
  File "instawow.cli", line 458, in match_all
  File "instawow.manager", line 729, in run
  File "instawow.utils", line 327, in make_progress_bar
  File "prompt_toolkit.shortcuts.progress_bar.base", line 146, in __init__
  File "asyncio.events", line 644, in get_event_loop
RuntimeError: There is no current event loop in thread 'MainThread'.
sys:1: RuntimeWarning: coroutine 'match_dir_names' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
SystemError
1 $ ./instawow -p wow1 --debug reconcile --auto
✓ curse:ace3
  installed Release-r1227
✓ curse:achievementsreminder
  installed 8.300
✓ curse:addons-cpu-usage
  installed v8.2.0.040
✓ curse:altoholic
  installed Altoholic 8.3.001
✓ curse:angry-assignments
  installed v1.13.0
✓ curse:angry-boss-reminders
  installed v0.10.0
✓ curse:ashranbuddy
  installed v7.2.0
✓ curse:astral-keys
  installed 3.25
✓ curse:aura-frames
  installed 1.5.10-Release
✓ curse:autoturnin
  installed 7.4.0
✓ curse:azeritetooltip
  installed 2.0.8
✓ curse:battle-pet-daily-tamer
  installed Battle_Pet_Daily_Tamer_3_0_6.zip
✓ curse:btw-quests
  installed v1.70.1
✓ curse:buyemall
  installed v3.5.7
✓ curse:championcommander
  installed 1.2.4
✓ curse:colorpickerplus
  installed r45
✓ curse:conslegion
  installed ConsLegion v1.31
✓ curse:daily-to-do
  installed Daily To Do 1.0.3
✓ curse:derangement-pet-battle-cooldowns
  installed DerangementPetBattleCooldowns-v1-1-5.zip
✓ curse:details
  installed DetailsRetail.8.3.0.7356.141
✓ curse:errorfilter
  installed v3.7
✓ curse:exorsus-raid-tools
  installed Exorsus Raid Tools v.4170
✓ curse:gtfo
  installed 4.56
✓ curse:garrison-mission-manager
  installed v59
✓ curse:gottagofast
  installed GottaGoFast_v3.1.1
✓ curse:handynotes-visions-of-nzoth
  installed v38
✓ curse:lefollowers
  installed LeFollowers
✓ curse:legion-wardrobe
  installed Legion Wardrobe v.3.0
✓ curse:libsharedmedia-3-0
  installed 8.2.0 v2 - r113
✓ curse:long-forgotten-hippogryph
  installed LongForgottenHippogryph v2.01.zip
✓ curse:shadoweduf-facade
  installed 1.5.3
✓ curse:master-plan
  installed 0.117
✓ curse:move-anything
  installed 17.1.0
✓ curse:npcscan
  installed 8.0.1.13
✓ curse:opie
  installed Walnut 6
✓ curse:omni-cc
  installed 8.3.6
✓ curse:pawn
  installed 2.3.34
✓ curse:personal-loot-helper
  installed PersonalLootHelper-2.21.zip
✓ curse:pet-journal-enhanced
  installed 2.9.30
✓ curse:pettracker
  installed 8.3.8
✓ curse:postal
  installed v3.6.2
✓ curse:premade-groups-filter
  installed 1.37
✓ curse:rclootcouncil
  installed 2.19.3
✓ curse:rarescanner
  installed RareScanner_8.6
✓ curse:rarity
  installed r698-release
✓ curse:rematch
  installed Rematch_4_10_5.zip
✓ curse:routes
  installed v1.6.3
✓ curse:scrap
  installed 8.3.2
✓ curse:sheepmonitor
  installed 1.23
✓ curse:simpletarget
  installed 1.0.2
✓ curse:simulationcraft
  installed v1.12.5
✓ curse:tidy-plates-threat-plates
  installed 9.2.4
✓ curse:tier-token-tooltip
  installed TTT v1.05
✓ curse:tip-tac
  installed 19.03.31
✓ curse:toaster
  installed 8.0.1.1
✓ curse:tokenize
  installed Version 1.0.3
✓ curse:tomtom
  installed v80300-1.1.4
✓ curse:tradeskill-master
  installed v4.9.38
✓ curse:wowhead-linker
  installed v1.4.5
✓ curse:world-quest-tracker
  installed v8.3.0.398
✓ curse:world-quests-list
  installed World Quests List v.9.2
✓ curse:icpu
  installed 8.2.1
✓ curse:idtip
  installed idTip-8.2.1
✓ curse:tdbattlepetscript
  installed 80100.01
✓ curse:tdbattlepetscript-rematch
  installed 80100.01
✓ wowi:22229-auto-safari-hat
  installed 1.6.2

   unreconciled    
-------------------
PetTracker_Breeds  
PetTracker_Switcher
PetTracker_Upgrades
$
```

**Comment by layday** [comment]
Thank you for report.  It looks like `prompt_toolkit` tried to get handle on the main loop which was previously closed. `prompt_toolkit` is used to display download progress.  Is this with the latest version of instawow?

**Comment by ciphersimian** [comment]
```
$ ./instawow --version
instawow, version 1.13.1
```

**Comment by layday** [comment]
This will be fixed in the next version.  Thanks again for the report.

**Comment by layday** [comment]
I'm curious why it wasn't able to reconcile the three PetTracker folders even though it installed PetTracker the second time.  Perhaps those folders were removed from the latest version of PetTracker.

**Comment by ciphersimian** [comment]
That was my assumption as well, I just went ahead and removed them.  Thanks for the quick fix.
