### ISSUE TITLE
Empty directory / imported instawow addons?

### ISSUE THREAD

**Issue by nayab9** [layday/instawow#7]
I'm noticing this stack trace when I attempt to list installed addons when the directory is empty.

Additional note: If I copy addons from a different machine which has used instawow for addon management, the new machine does not detect any of the addons and instead spits out the below stacktrace, is this expected? Any chance we can freely move instawow managed addon directories across installations and instawow can pick them up?

```
Traceback (most recent call last):
  File "/home/user/.local/bin/instawow", line 10, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/user/.local/lib/python3.7/site-packages/instawow/cli.py", line 278, in list_installed
    *(f'[{e}]' for e in toc_entries))))
  File "/home/user/.local/lib/python3.7/site-packages/instawow/cli.py", line 51, in _tabulate
    table.set_cols_align(f'r{"l" * len(rows[0])}')
```

**Comment by layday** [comment]
> Any chance we can freely move instawow managed addon directories across installations and instawow can pick them up?

Yep, you just need to copy the database from the old machine.  Looks like you're on Linux so you'll find it at `$HOME/.config/instawow/db.sqlite`.

**Comment by layday** [comment]
No follow-up so I assume that worked for you and the error's been fixed on master.
