### ISSUE TITLE
Windows versions don't work at all?

### ISSUE THREAD

**Issue by highend** [layday/instawow#76]
Hi,

I've tried the current (binaries) v1.23.1 under Windows Server 2019 x64.

Retail WoW folder: ```D:\Games\World of Warcraft\_retail_```
and I've put the CLI version here: ```D:\Games\World of Warcraft\Instawow\instawow.exe```

I only get this when I invoke it via ```instawow.exe reconcile```
```
Traceback (most recent call last):
  File "instawow.__main__", line 4, in <module>
  File "click.core", line 829, in __call__
  File "click.core", line 782, in main
  File "click.core", line 1259, in invoke
  File "click.core", line 1066, in invoke
  File "click.core", line 610, in invoke
  File "click.decorators", line 21, in new_func
  File "instawow.cli", line 434, in reconcile
  File "instawow.utils", line 69, in __get__
  File "instawow.cli", line 102, in m
  File "instawow.config", line 109, in read
  File "instawow.config", line 96, in get_dummy_config
  File "pydantic.main", line 572, in parse_obj
  File "pydantic.env_settings", line 38, in __init__
  File "pydantic.main", line 398, in __init__
  File "pydantic.main", line 1034, in validate_model
  File "pydantic.fields", line 737, in validate
  File "pydantic.fields", line 913, in _apply_validators
  File "pydantic.class_validators", line 277, in <lambda>
  File "instawow.config", line 75, in _validate_expand_path
  File "instawow.config", line 31, in _validate_expand_path
  File "pathlib", line 1161, in resolve
  File "pathlib", line 205, in resolve
OSError: [WinError 1] Incorrect function: 'R:\\TEMP'
SystemError
```

For clarification: ```R:\TEMP``` is the system wide ```%TEMP%``` folder (defined in the environment variables)

The same happens with the GUI version, only that the output is done in a message requester.

**Comment by layday** [comment]
Thanks for the report.  It looks like this is a Python bug: https://bugs.python.org/issue31842.  A simple workaround would be to use `os.path` instead.

**Comment by layday** [comment]
Please try [v1.23.2](https://github.com/layday/instawow/releases/tag/v1.23.2) which I just published.

**Comment by highend** [comment]
Fixed with that release, thanks!
