### ISSUE TITLE
instawow-gui does not start anymore

### ISSUE THREAD

**Issue by rdenhof** [layday/instawow#86]
With version 1.29 installed over working version 1.28 application does not start anymore. Python process appears in Windows task manager and disappears directly afterwards. Used .msi installer package. Installed 1.28 again which works now.

**Comment by layday** [comment]
Could you attach your error log? It can be found in `%APPDATA%/Roaming/instawow/profiles/__jsonrpc__`.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rdenhof** [comment]
Unfortunately the file is empty. Seems to be crashing during early startup.

**Comment by layday** [comment]
I don't have access to a Windows machine to investigate so I'll pull the Windows installer from the latest release for now.  Sorry for the trouble.

**Comment by layday** [comment]
(If you're feeling brave, you can try installing the latest development version from https://github.com/layday/instawow/actions/runs/1291525564, to see it if works.)

**Comment by layday** [comment]
Should be fixed in [v1.29.1](https://github.com/layday/instawow/releases/tag/v1.29.1).  Thanks for the report!

**Comment by rdenhof** [comment]
Thanks for fixing, this works... but now I'm facing a strange issue as I tried to cleanup installation/configuration in Appdata directory completely in the meantime. After reinstalling from scratch I see this error in logs and my existing addons are not recognized:

`2021-10-01 21:46:33.137 | ERROR    | logging:callHandlers:1649 - Can't locate revision identified by '9b8df9661cdb'
Traceback (most recent call last):

  File "instawow_gui\json_rpc_server.py", line 488, in schedule

KeyError: 'retail_profile'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "alembic\script\base.py", line 227, in _catch_revision_errors

  File "alembic\script\base.py", line 289, in get_revisions

  File "alembic\script\revision.py", line 525, in get_revisions

  File "alembic\script\revision.py", line 525, in <listcomp>

  File "alembic\script\revision.py", line 549, in get_revisions

  File "alembic\script\revision.py", line 550, in <genexpr>

  File "alembic\script\revision.py", line 619, in _revision_for_ident

alembic.script.revision.ResolutionError: No such revision or branch '9b8df9661cdb'


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "toga_winforms\app.py", line 199, in run_app

  File "toga_winforms\libs\proactor.py", line 99, in run_forever

  File "toga_winforms\libs\proactor.py", line 140, in run_once_recurring

  File "asyncio\base_events.py", line 1859, in _run_once

  File "asyncio\events.py", line 81, in _run

> File "aiohttp_rpc\middlewares.py", line 25, in exception_middleware

  File "aiohttp_rpc\middlewares.py", line 20, in extra_args_middleware

  File "aiohttp_rpc\server\base.py", line 168, in _process_single_request
  File "instawow_gui\json_rpc_server.py", line 141, in respond

  File "instawow_gui\json_rpc_server.py", line 513, in run

  File "asyncio\tasks.py", line 455, in wait_for

  File "instawow_gui\json_rpc_server.py", line 493, in schedule

  File "instawow\manager.py", line 362, in from_config

  File "instawow\manager.py", line 226, in prepare_database

  File "alembic\command.py", line 613, in stamp

  File "alembic\script\base.py", line 563, in run_env

  File "alembic\util\pyfiles.py", line 98, in load_python_file

  File "alembic\util\pyfiles.py", line 108, in load_module_py

  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "instawow\migrations\env.py", line 39, in <module>

  File "instawow\migrations\env.py", line 35, in main

  File "instawow\migrations\env.py", line 28, in run_online

  File "<string>", line 8, in run_migrations

  File "alembic\runtime\environment.py", line 851, in run_migrations

  File "alembic\runtime\migration.py", line 600, in run_migrations

  File "alembic\command.py", line 601, in do_stamp

  File "alembic\script\base.py", line 485, in _stamp_revs

  File "alembic\script\base.py", line 288, in get_revisions

  File "contextlib.py", line 131, in __exit__

  File "alembic\script\base.py", line 259, in _catch_revision_errors

alembic.util.exc.CommandError: Can't locate revision identified by '9b8df9661cdb'
`

Do you have an idea, what went wong and how it can be fixed? Did I miss s.th. during cleanup?

**Comment by layday** [comment]
That was an issue with the compiled Python bytecode not being able to be used for database migrations.  I've reuploaded v1.29.1; please delete your configuration folder and reinstall.

**Comment by rdenhof** [comment]
Thanks a lot for your quick fixes, now it's working like a charme!
